### ISSUE TITLE
Какая разница для пустых параграфов?

### ISSUE THREAD

**Issue by maliutin** [gribuser/fb2#1]
Есть ли смысловая разница для `<empty-line />`, `<p />` и `<p></p>`?

**Comment by gribuser** [comment]
Аналог `<empty-line />` в XHTML скорей `<hr/>`, чем `<p/>|<br/>`

**Comment by maliutin** [comment]
Спасибо за ответ.
Таким образом если пользователь хочет иметь пустой параграф то нужно использовать `<p/>`. или `<p></p>`?

**Comment by gribuser** [comment]
Короткий ответ звучит как "пользователь, конечно же, **не хочет** иметь пустой параграф". Но если непременно надо прострелить себе ногу, то да.

**Comment by maliutin** [comment]
@gribuser А [здесь][1] сказано:

> Элемент позволяет вставить пустую строку между двумя абзацами текста.

Так может лучше ассоциировать `<emty-line />` с пустой строкой?

Что рекомендовано делать читалкам? 

Попутный вопрос. А будут ли переноситься описание элементов от [сюда][2] сюда?

[1]: http://fictionbook.org/index.php/%D0%AD%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82_empty-line
[2]: http://fictionbook.org/index.php/%D0%AD%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%8B_%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%B0_FictionBook

**Comment by gribuser** [comment]
Нет, это "разрыв в тексте", который по высоте должен превышать пустую строку, как минимум. А может еще и быть дополнительно оформлен. Разрыв в полторы строки, на маленьком экране можно вообще с нового экрана начать, я бы так советовал. Дешевое решение - праравнять к пустой строке, конечно.
Описания дополнительно переносить не планировал. И вообще fb2 это уже прошлый век, мы над fb3
работаем.
https://github.com/gribuser/FB3

**Comment by maliutin** [comment]
Понял. `<empty-line />` пустая строка с дополнительным смыслом.

А саму документация на fictionbook.org оставят, чтобы потом на основании её можно было делать fb2 читалки?  

Также FB2 имеет пространство `http://www.gribuser.ru/xml/fictionbook/2.0`. Там схема останется?

**Comment by gribuser** [comment]
Ну пока оно там валяется и валяется. Рано или поздно грохнется, наверное, но целенаправленно никто ничего ломать не будет.

**Comment by maliutin** [comment]
@gribuser Так может сделать редирект с `http://www.gribuser.ru/xml/fictionbook/2.0` на `https://github.com/gribuser/fb2/blob/master/FictionBook2.0.xsd`. Пусть народ привыкает.

**Comment by gribuser** [comment]
Неплохой план
